import type { Metadata } from 'next'
import './globals.scss'
import { Header } from '@/components/template/Header/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />

        <main>
          {children}
        </main>

      </body>
    </html>
  )
}
