import type { Metadata } from 'next';

import { Footer } from '@/components/template/Footer/Footer';
import { Header } from '@/components/template/Header/Header';

import './globals.scss';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
    return (
        <html lang="en">
            <body>
                <Header />

                <main>{children}</main>

                <Footer />
            </body>
        </html>
    );
}
